services:
  namenode:
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    image: apache/hadoop:3
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    healthcheck:
      test: ["CMD", "hdfs", "dfsadmin", "-report"]
      interval: 30s
      timeout: 10s
      retries: 5

  datanode:
    image: apache/hadoop:3
    hostname: datanode
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
    # depends_on:
    #   namenode:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "hdfs", "dfsadmin", "-report"]
      interval: 30s
      timeout: 10s
      retries: 5

  resourcemanager:
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    image: apache/hadoop:3
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh
    # depends_on:
    #   namenode:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "jps | grep ResourceManager"]
      interval: 30s
      timeout: 10s
      retries: 5

  nodemanager:
    image: apache/hadoop:3
    hostname: nodemanager
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config
    # depends_on:
    #   resourcemanager:
    #     condition: service_healthy

  # MapReduce History Server
  historyserver:
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    image: apache/hadoop:3
    hostname: historyserver
    command: ["mapred", "historyserver"]
    ports:
      - 19888:19888
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh
    # depends_on:
    #   namenode:
    #     condition: service_healthy
    #   resourcemanager:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19888/ws/v1/history/info"]
      interval: 30s
      timeout: 10s
      retries: 5

  # MapReduce Client/Submit Node
  mapreduce-client:
    image: apache/hadoop:3
    hostname: mapreduce-client
    command: ["tail", "-f", "/dev/null"]  # Keep container running
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh
      - ./mapreduce-jobs:/opt/mapreduce-jobs  # Mount directory for job files
    # depends_on:
    #   namenode:
    #     condition: service_healthy
    #   resourcemanager:
    #     condition: service_healthy
    #   historyserver:
    #     condition: service_healthy

  # Hive Metastore Database (PostgreSQL)
  hive-metastore-db:
    image: postgres:13
    hostname: hive-metastore-db
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive123
    volumes:
      - hive-metastore-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d metastore"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Hive Metastore Service
  hive-metastore:
    image: apache/hive:4.0.0
    hostname: hive-metastore
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: "-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://hive-metastore-db:5432/metastore -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=hive123"
    env_file:
      - ./config
    ports:
      - 9083:9083
    # depends_on:
    #   namenode:
    #     condition: service_healthy
    #   hive-metastore-db:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9083"]
      interval: 30s
      timeout: 10s
      retries: 5

  # HiveServer2
  hiveserver2:
    image: apache/hive:4.0.0
    hostname: hiveserver2
    environment:
      SERVICE_NAME: hiveserver2
      SERVICE_OPTS: "-Dhive.metastore.uris=thrift://hive-metastore:9083"
      IS_RESUME: "true"
    env_file:
      - ./config
    ports:
      - 10000:10000  # HiveServer2 Thrift port
      - 10002:10002  # HiveServer2 Web UI
    volumes:
      - ./test.sh:/opt/test.sh
    # depends_on:
    #   namenode:
    #     condition: service_healthy
    #   hive-metastore:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "10000"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Hive Client for running queries
  hive-client:
    image: apache/hive:4.0.0
    hostname: hive-client
    command: ["tail", "-f", "/dev/null"]  # Keep container running
    environment:
      SERVICE_OPTS: "-Dhive.metastore.uris=thrift://hive-metastore:9083"
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh
      - ./hive-queries:/opt/hive-queries  # Mount directory for query files
    # depends_on:
    #   namenode:
    #     condition: service_healthy
    #   hive-metastore:
    #     condition: service_healthy
    #   hiveserver2:
    #     condition: service_healthy

volumes:
  hive-metastore-db-data: